services:
  - type: web
    name: zap-insolite-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars: []
    plan: free
    region: oregon
    build:
      packages:
        - ffmpeg
